### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by kitze** [stuartcryan/lastpass-alfred-workflow#3] opened 2015-07-23 15:09 UTC
<img width="697" alt="screen shot 2015-07-23 at 17 56 25" src="https://cloud.githubusercontent.com/assets/1160594/8853629/37f41d26-3164-11e5-8186-fb29fba41d9a.png">
I've edited the workflow and the terminal says that i'm logged in but the app says that i'm not. What can i do?

**Comment by stuartcryan** [comment] 2015-07-24 11:43
Hi Kitze,
Hmm that is really quite unusual. Can you please open up the Alfred workflow configuration panel, click on the Lastpass workflow, turn on debugging (and set it to All information) then output the results here (please make sure to redact any private information from what you paste in here). I am guessing you are getting an error but the question is... why... (there must be an unhandled exception of some sort).

Also what happens if you run the following in a command prompt/terminal after you have run lplogin:
lpass ls

(as that would be the command that is seemingly erroring out).

Look forward to hearing from you.
Cheers,
Stuart

**Comment by kitze** [comment] 2015-07-24 15:09
Huh, suddenly it works now, i don't know how. But nothing happens when i press enter on an selected item, no matter if it is a secure note or a password. Should it copy the pass or note to my clipboard?

**Comment by stuartcryan** [comment] 2015-07-25 03:04
Hi Kitze,
That is REALLY strange, any chance you would be open to me doing a Teamviewer remote session with you to have a look for myself?
Cheers,
Stuart

**Comment by kitze** [comment] 2015-07-25 20:55
Yeah sure, i'll setup few fake passwords and notes so you can take a look. My skype id is kristijan.mkd, add me there and we'll setup a session.

**Comment by perks** [comment] 2015-08-16 21:11
Hey, I am getting the same error as above:

Below is the debugging information logged from doing lplogin -> lp [search]

```
INFO: alfred.workflow.input.keyword] Processing output 'alfred.workflow.action.terminalcommand' with arg ''
[ERROR: alfred.workflow.input.scriptfilter] Code 1: <?xml version="1.0"?>
<items>
<item uid="error-login"><arg>'error-login', ''</arg><title>It appears you are not logged in to LastPass.</title><subtitle>Please login using the 'lplogin' command or press 'ctrl' + enter to login now.</subtitle><icon>icon.png</icon></item>
</items>
[ERROR: alfred.workflow.input.scriptfilter] Code 1: <?xml version="1.0"?>
<items>
<item uid="error-login"><arg>'error-login', ''</arg><title>It appears you are not logged in to LastPass.</title><subtitle>Please login using the 'lplogin' command or press 'ctrl' + enter to login now.</subtitle><icon>icon.png</icon></item>
</items>
[INFO: alfred.workflow.input.scriptfilter] Processing output 'alfred.workflow.action.script' with arg ''error-login', '''
```

**Comment by stuartcryan** [comment] 2015-08-18 05:31
Hi Perks, HMMM that is interesting, I will have a play with your fix and may potentially look at doing it straight in perl instead.

Thanks for the heads up, (and the extended testing) I will do some internal testing and get back to you.

**Comment by stuartcryan** [comment] 2015-08-18 05:38
Hi Perks, That file is actually no longer used (at all) by the workflow, I had forgotten to remove it when it was deprecated so it *shouldn't* have been causing issues.

I have put together a beta version here https://dl.dropboxusercontent.com/u/9093155/alfred-workflows/stuartcryan-lastpass-cli/LastPassCLI_1.2.1_beta.alfredworkflow are you possibly able to give that a whirl please?

Note as this is a new version, you will need to do the following:
run 'lpsetemail yourname@example.com'

That will set your email address for the workflow (rather than having to edit it inline).

Please let me know how you go.
Cheers,
Stuart

**Comment by perks** [comment] 2015-08-18 17:47
Hey Stuart,

Thanks for the beta workflow, I gave it some very cursory use and here's what I came up with:

Booting up Alfred and doing lplogin -> lpsearch seemed to work great. I noticed that the beta doesn't do any caching to file (live parses output I guess) so maybe the problem was over in there?

Or it could have been related to this bug I found. If you do 'lplogout' and then relogin again, it will prompt you again to login saying that you have not done so (even though you are). Funny enough, to test that I actually was, I ran `lpass ls` at my terminal prompt, and once I did that, it seemed to have made the Alfred workflow recognize I was logged in. Maybe a flush issue/context issue with the way Alfred is making calls to `lpass`? I'm not too sure I didn't spend too much time looking into the code

Anyways the bug above is very reproducible on my end, so maybe that will he

Below is debug info: (Successful fetch)
```
Starting debug for 'LastPass CLI'

[ERROR: alfred.workflow.input.scriptfilter] Code 2: <?xml version="1.0"?>
<items>
<item uid="error-nonefound"><arg>'error-nonefound'</arg><title>256 :  :  No search results matching your query found.</title><subtitle>Please try again with a different query.</subtitle><icon>icon.png</icon></item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?>
<items>
<item uid="REMOVED"><arg>'REMOVED', 'REMOVED'</arg><title>REMOVED</title><subtitle></subtitle><icon>icon.png</icon></item>
</items>
```

**Comment by stuartcryan** [comment] 2015-08-19 08:51
Hi Perks,
That is very interesting, I have worked on a new beta version (not yet committed to the public repo) that is currently in testing by someone else, can you please give this a try.

https://dl.dropboxusercontent.com/u/9093155/alfred-workflows/stuartcryan-lastpass-cli/LastPassCLI_1.2.2_beta_sync_speed.alfredworkflow

It works around the issue by forcing a sync to be performed after logging in. This has several benefits in that it fixes the issue with logging in after you have logged out, as well as speeds up the response of the workflow in providing back results.

Please let me know how you go.
Cheers,
Stuart

**Comment by stuartcryan** [comment] 2015-08-26 11:14
Hi kitze and Perks,
Just checking in, has this been successfully resolved for you both in the new version?
Cheers,
Stuart

**Comment by perks** [comment] 2015-08-27 21:13
Hey Stuart,

The new update works great so far, so thanks! It seems that the login/logout thing is working a lot better. The only thing now is that sometimes the 'login' script doesn't execute in my shell properly (Using zsh with iterm 2.11 + alfred applescript for iterm), complaining of mismatched quotations or a "short lived session". However sometimes it does work, so I'll keep a look out for whats happening

**Comment by stuartcryan** [comment] 2016-01-05 07:22
Hi Perks,
I am working on a new version which changes how the login process works (which basically transitions to AppleScript rather than a pure bash script).

When the beta is ready I will let you know here as I am curious to see if it resolves your issue.
Kind Regards,
Stuart

**Comment by perks** [comment] 2016-01-07 20:43
@stuartcryan sounds awesome, looking forward to it!

**Comment by stuartcryan** [comment] 2016-01-10 02:59
Hi Guys,
Have a new beta version ready for testing with quite a few changes.

https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4_beta.alfredworkflow

Changes in this release:
1. Login process completely changed over to use AppleScript
2. Login password prompt now uses an AppleScript password prompt
3. Fix to allow you to search for words in any order
4. Other minor general tweaks
5. Has now been tested with a Vault with over 30,000 items for performance tweaks. (I have since been told by LastPass support their soft limit is significantly lower than this :D explains why I was having some issues even testing).
6. More resilient escaping of text in the XML to ensure that special characters should not cause any issues
7. Fixed missing quotes in some areas that could cause issues with spaces
8. Squashed a little regex bug and wiped up the goo.

Look forward to your thoughts.
Cheers,
Stuart

**Comment by stuartcryan** [comment] 2016-01-10 10:25
Forgot to mention (added to my last comment but adding here for good measure).

**PLEASE NOTE** I forgot to mention, this beta requires LastPass CLI v 0.7.1 or higher, it is not backwards compatible. This is due to a new feature that I worked with Bob from LastPass on to enable the use of an external scripting mechanism for getting the password. Note, for those security concerned, all that the external AppleScript does is request your password and output it to STDOUT which the LastPass command takes in (as now supported by the official CLI).

**Comment by perks** [comment] 2016-01-11 17:55
@stuartcryan Gave this a run yesterday, and everything works a lot cleaner!

Especially good is getting rid of the login system that opened a terminal session to do the login, moving to Applescript probably will solve a lot of the issues here involving `lplogin` problems  (I know before my zsh setup would react weirdly to it at times).

Also like the touch of adding email/logout time to the keychain! 

Tried a bunch of logging out -> logging in -> search, and so far haven't run into any problems! This should be ready to add to the repo I think.

**Comment by stuartcryan** [comment] 2016-01-11 20:13
Hi Chris,
Thanks for that. I was so glad I could come up with that solution with the lastpass team to use any external script you wanted to handle the login process. It just makes it FAR FAR cleaner to work with.

Thank you for testing, I have one (possible) bug that I need to have a look at in regards to spaces in the path where alfredpreferences are saved and then all going well there I will look to release. So please let me know if you have any issues in the coming days as you use it in your normal flow.

Cheers,
Stuart

**Comment by stuartcryan** [comment] 2016-01-11 20:51
All righty minor update to 1.4.1 fixes said issue with spaces in the path.

If all goes OK with the few testers I have got in the next 24 hours... I think this one will be the next official release:

https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.1_beta.alfredworkflow

**Comment by stuartcryan** [comment] 2016-01-12 09:29
Annnd another one for you which was raised by a beta tester. This improves the way we handle things if you have not yet run lplogin. This actually could not be fixed until we had the new login system in place.

Basically, things should be a lot cleaner when you reboot your computer. For example if you attempt to run "lp xxx" before you are logged in, it will now correctly detect that you are not logged in and you can press CTRL + Enter to log in. The script will then log you in, and as soon as the login process is done, present the Alfred window with "lp " populated so you can enter your search.

https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.2_beta.alfredworkflow

Barring any major bugs, this should hopefully be good in 24 hours time. Happy for you both to test if you would like.

**Comment by stuartcryan** [comment] 2016-01-14 00:50
All righty all, new version officially released :) can be dowloaded from the main repository but the only difference in the binary is removing the word BETA from the description text :D

**Closed by stuartcryan** 2016-01-14 00:50 UTC
Labels: bug
