### ISSUE TITLE
Workflow doesn't log in to Lastpass

### ISSUE THREAD

**Issue by RowanKaag** [stuartcryan/lastpass-alfred-workflow#33] opened 2016-05-18 14:08 UTC
**lp a**
```
Starting debug for 'LastPass CLI'

[2016-05-18 16:05:55][ERROR: input.scriptfilter] Code 1: <?xml version="1.0"?>
<items>
<item uid="error-login"><arg>scriptlocationnotset</arg><title>It appears you are not logged in to LastPass.</title><subtitle>Please login using the 'lplogin' command or press 'ctrl' + enter to login now.</subtitle><icon>icon.png</icon></item>
</items>

[2016-05-18 16:21:03][ERROR: action.script] Usage: /usr/local/bin/lpass show [--sync=auto|now|no] [--clip, -c] [--expand-multi, -x] [--all|--username|--password|--url|--notes|--field=FIELD|--id|--name] [--basic-regexp, -G|--fixed-strings, -F] [--color=auto|never|always] {UNIQUENAME|UNIQUEID}
```
**lplogin**
```
[2016-05-18 16:06:01][ERROR: action.script] 2845:2846: syntax error: Expected end of line but found “"”. (-2741)
```
**lpass cli**
```
$ lpass login *****@*****.**
Success: Logged in as ********
```

I'm supposing it has something to do with OS X 10.11.5 and/or Alfred 3.
Didn't have problems with the 'scriptlocationnotset' before.

**Comment by colbyfayock** [comment] 2016-05-19 18:05
@stuartcryan this is fixed updating Alfred 2 to Alfred 3, for Alfred 3 users in here:

<img width="569" alt="screen shot on 2016-05-19 at 14-03-49" src="https://cloud.githubusercontent.com/assets/1045274/15404244/9201c63a-1dca-11e6-9e70-1ab48a6f3b16.png">

Was thinking of doing a PR, but no idea how to compile Alfred workflows or how to handle using either version in there :)

**Comment by RowanKaag** [comment] 2016-05-19 21:55
@colbyfayock what did you do to fix it? I'm rather dependend on this workflow 😳

**Comment by stuartcryan** [comment] 2016-05-19 22:34
Hi All,
Colby, thanks for pointing that out, can you both please test this new beta version. And ensure it resolves the issue.

Download from: https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.6_beta1.alfredworkflow

Once you have confirmed I will prepare a cross compatible version and then update it.
Cheers,
Stuart

**Comment by colbyfayock** [comment] 2016-05-20 14:56
Yup, that does the trick. Thanks :D

**Comment by RowanKaag** [comment] 2016-05-20 19:13
Did the trick indeed!

**Comment by zlanich** [comment] 2016-05-21 05:21
That worked!

**Comment by johnnypea** [comment] 2016-05-21 16:09
+1

**Comment by timshutes** [comment] 2016-06-11 18:04
Any update on this? Still broken on Mac - no login

**Comment by colbyfayock** [comment] 2016-06-11 21:08
@timshutes did you try the solution he provided above?

**Comment by timshutes** [comment] 2016-06-11 21:47
the beta version is - but there is still no fix for the cross-compatible version

**Comment by joey-postma** [comment] 2016-06-21 13:35
I was getting the same error:
[ERROR: action.script] 2845:2846: syntax error: Expected end of line but found “"”. (-2741)

I tried the beta version but now I get another error:
[ERROR: action.script] 2637:2649: execution error: The variable lpass_binary is not defined. (-2753)

I followed every step in the documentation: http://www.packal.org/workflow/lastpass-cli-workflow-alfred

However when I get to the login step, I don't get the popup because of this error.

Please let me know if there is something else I can try.

Thanks

**Comment by stuartcryan** [comment] 2016-07-06 01:04
Ladies and gentlemen... this has now been fixed and merged in and is now released.

I sincerely apologise for the delay... my masters course at university was extremely intense for me this semester and had to take priority.

@joey-postma please try the new version out... if there are any issues please log a new issue.

**Closed by stuartcryan** 2016-07-06 01:04 UTC

**Comment by tshaiman** [comment] 2019-07-11 13:28
Alfred version 4 with LastPass v1.4.7 still has this issue **as of July 2019 :**

[16:27:26.562] LastPass CLI[Keyword] Processing complete
[16:27:26.562] LastPass CLI[Keyword] Passing output 'tshaiman@outlook.com' to Run Script
[16:27:26.664] LastPass CLI[Run Script] Processing complete
[16:27:26.667] LastPass CLI[Run Script] Passing output 'tshaiman@outlook.com
' to Post Notification
[16:27:31.936] LastPass CLI[Keyword] Processing complete
[16:27:31.937] LastPass CLI[Keyword] Passing output '' to Run Script
[16:27:32.122] ERROR: LastPass CLI[Run Script] 2845:2846: syntax error: Expected end of line but found “"”. (-2741)

**Comment by yogipatel5** [comment] 2019-08-01 20:54
@tshaiman Having another issues.. but similar ending. You seem to be getting farther than I am. 

[16:51:38.119] LastPass CLI[Keyword] Processing complete
[16:51:38.121] LastPass CLI[Keyword] Passing output '' to Run Script
[16:51:38.319] ERROR: LastPass CLI[Run Script] 2843:2844: syntax error: Expected end of line but found “"”. (-2741)

**Comment by ascandroli** [comment] 2019-10-15 11:13
@tshaiman @yogipatel5 I just found the solution for that issue in #55
